# Generated by Django 4.2 on 2025-02-17 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_default_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_email',
            new_name='default_user_email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_name',
        ),
    ]
