# Generated by Django 4.2 on 2025-01-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
