# Generated by Django 4.2 on 2025-01-28 17:36

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pattern',
            options={},
        ),
        migrations.AddField(
            model_name='pattern',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
