# Generated by Django 4.2 on 2025-01-22 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0002_pattern_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pattern',
            options={},
        ),
    ]
