# Generated by Django 4.2 on 2025-02-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
