# Generated by Django 4.2 on 2025-01-28 15:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0004_alter_pattern_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
