# Generated by Django 4.2 on 2025-02-28 16:42

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0005_alter_pattern_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=85, scale=None, size=[800, 800], upload_to='patterns/'),
        ),
    ]
